### ISSUE TITLE
GCC 8

### ISSUE THREAD

**Issue by tower120** [DaemonSnake/unconstexpr#1]
I know, you wrote that it is intended to work with gcc 7 only, but I wonder, is this [http://b.atch.se/posts/constexpr-counter/#solution](http://b.atch.se/posts/constexpr-counter/#solution) in general still valid? I mean standard-wise.

I just tried gcc 8 and clang - and no luck.
[https://godbolt.org/g/HH3cRL](https://godbolt.org/g/HH3cRL)

**Comment by DaemonSnake** [comment]
I couldn't tell you, I'm not aware of any standard change that would make it suddenly illegal.
It's probably a new optimisation from GCC's team.
Standard compliance is no guarantee when you're trying to abuse it.

**Comment by tower120** [comment]
I see, thanks.
